### PR TITLE
Prevent remounting previousPage when doing page transition

### LINKED ISSUE #191: Page Transitioning causes unwanted mounting of previous page
The current page transitioning will render both the current and the previous page in order to animate the transition. The previous page is unmounted and mounted again.

Because of this, the previous page's lifecycle methods will be called again. For example,  `componentDidMount` is sometimes used to load data, track pageviews or operate on the DOM. Therefore, it can be quite expensive.

To, me this is an unwanted side effect of the current implementation. In my current project it schews the analytics, because I'm tracking pageviews in `componentDidMount`.

I'd love to investigate a different implementation, where perhaps we can take some cues from React TransitionGroup etc.

### PR DESCRIPTION
**Pull request by ruisalgado**
fixes #191

### CODE REVIEW

**Comment by ruisalgado** [comment]
would probably be best to get #197 merged before this one

**Comment by pascalw** [comment]
Looks good to me! Did you verify it indeed prevents remounting?

**Comment by ruisalgado** [comment]
@pascalw yap it does

**Comment by pascalw** [comment]
Awesome. I've merged the PR that moves pageTransitionSupport to the library so if you rebase against master we can merge this too 🚀

**Comment by leonderijke** [comment]
I incorporated this in my current project. It works like a charm! 👍

**Comment by ruisalgado** [comment]
@leonderijke I incorporated the changes we discussed over slack earlier this week, to prevent multiple versions of the same dependency. Can you give this PR a quick re-review and then :shipit: ?

**Pull request merged**
