### PR TITLE
Bugfix/version parameter returns 1.0.0

### LINKED ISSUE #141: Maji 2 reports wrong version number
```
~/code/maji 2-0-stable 13:25:42
➤ npm link
/usr/local/bin/maji -> /usr/local/lib/node_modules/maji/lib/cli.js
/usr/local/bin/maji-dev-server -> /usr/local/lib/node_modules/maji/src/maji-dev-server.js
/usr/local/lib/node_modules/maji -> /Users/roel/code/maji
~/code/maji 2-0-stable 13:26:10
➤ maji --version
1.0.0
```

### PR DESCRIPTION
**Pull request by eirvandelden**
This fixes #141

### CODE REVIEW

**Comment by eirvandelden** [comment]
@pascalw @matthijsgroen I changed the response from `bin/maji --version` from a hardcode `1.0.0` to a hardcode `2.0.0`. Is there also a way to dynamically load the version from the package.json?

**Comment by eirvandelden** [comment]
@pascalw @matthijsgroen Okay, now I just need to know how rebuild the scripts and this should work 😅

**Comment by eirvandelden** [comment]
Now it's ready for review!

**Comment by eirvandelden** [comment]
@matthijsgroen @pascalw Please review :)

**Comment by pascalw** [comment]
Thanks 👍

**Pull request merged**
