### PR TITLE
Remove Maji plugin management in favor of Cordova plugin management

### PR DESCRIPTION
**Pull request by pascalw**
This is a breaking change and therefor targets the `2-0-stable` branch.

### CODE REVIEW

**Comment by matthijsgroen** [comment]
Will this also close #72 ?

**Comment by pascalw** [comment]
Yes

**Comment by matthijsgroen** [comment]
@pascalw What is left before we can merge this?

**Comment by pascalw** [comment]
I'll add a section to the upgrade guide and then we're good.

**Comment by pascalw** [comment]
@matthijsgroen done!

**Comment by pascalw** [comment]
Triggering rebuild, package.json referred to wrong Maji branch.

--

Jenkins test this please

**Comment by matthijsgroen** [comment]
@pascalw this can be merged right?

**Comment by pascalw** [comment]
Yes.

**Pull request merged**
