### PR TITLE
Make framework CSS classes more specific...

### PR DESCRIPTION
**Pull request by RoelN**
...so they won't clash with user CSS.

### CODE REVIEW

**Comment by RoelN** [comment]
Take heed: creating a new Maji project doesn't work, as it throws some inexplicable error that I can't figure out. Parked this for now. If anyone can help me with what going on, that'd be much appreciated!

boink

**Comment by pascalw** [comment]
Hey @RoelN is still still something you want to pursue? If yes can you please rebase the branch against `2-0-stable`?

**Comment by RoelN** [comment]
@pascalw Yes, I would like to tackle this. As discussed with @matthijsgroen I would also like to tackle some other things with the CSS of Maji and the project template. When time permits I'll either rebase or reimplement this.

**Comment by pascalw** [comment]
@RoelN I'm contemplating wether or not this should go into 2.0. It's a potentially breaking change though at the other hand these are classes that are/should be only set my Maji itself (expect for `.page` -> `.maji-page`) so this could be changed later too. What do you think?

**Pull request closed without merging**
