### PR TITLE
Upgrade cordova from 4.2.1 to 4.3.0

### PR DESCRIPTION
**Pull request by stefanvr**
Move to the latest version in 4.x.x version

### CODE REVIEW

**Comment by stefanvr** [comment]
Moving from 4.2.1 to 4.3.0 it seems that the default API level from android changes from 19 to 21.

**Comment by pascalw** [comment]
You should be able to set the minimumSdkVersion in your config.xml. Do mind
that certain plugins may require a higher API level.

Op woensdag 13 mei 2015 heeft Stefan van Raaphorst <notifications@github.com>
het volgende geschreven:

> Moving from 4.2.1 to 4.3.0 it seems that the default API level from
> android changes from 19 to 21.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kabisaict/maji/pull/36#issuecomment-101791770>.
>


-- 

Met vriendelijke groet,

Pascal Widdershoven
Kabisa

Marconilaan 8, 6003 DD, Weert
Kleine Gartmanplantsoen 10, 1017 RR, Amsterdam

email: pascal.widdershoven@kabisa.nl
web: http://www.kabisa.nl
mobile: +31 (0) 6 814 77 020
tel: +31 (0) 495 430 798
support tel: +31 (0) 495 430 593
support web: http://support.kabisa.nl
CoC: 14090089

**Comment by flarik** [comment]
I actually think we should target API 15 or 16

http://data.wurfl.io/MOVR/pdf/2015_q1/MOVR_2015_q1.pdf

source: http://www.scientiamobile.com/page/movr-mobile-overview-report

**Comment by pascalw** [comment]
Target doesn't mean it only runs there. It's perfectly fine to target 19
and have 14 as a minimum. This allows newer versions to take advantage of
new features like the Chrome backed webview on >= 4.4.

Op woensdag 13 mei 2015 heeft Frodo Larik <notifications@github.com> het
volgende geschreven:

> I actually think we should target API 15 or 16
>
> http://data.wurfl.io/MOVR/pdf/2015_q1/MOVR_2015_q1.pdf
>
> source: http://www.scientiamobile.com/page/movr-mobile-overview-report
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kabisaict/maji/pull/36#issuecomment-101807706>.
>


-- 

Met vriendelijke groet,

Pascal Widdershoven
Kabisa

Marconilaan 8, 6003 DD, Weert
Kleine Gartmanplantsoen 10, 1017 RR, Amsterdam

email: pascal.widdershoven@kabisa.nl
web: http://www.kabisa.nl
mobile: +31 (0) 6 814 77 020
tel: +31 (0) 495 430 798
support tel: +31 (0) 495 430 593
support web: http://support.kabisa.nl
CoC: 14090089

**Comment by flarik** [comment]
Yes! that's what i mean, something like this in your config.xml

```xml
<preference name="android-minSdkVersion" value="15" />
<preference name="android-targetSdkVersion" value="19" />
```

Android 5.x (target 21+) is still not used much.

iosvsandroidt

**Comment by pascalw** [comment]
Sounds like a plan! :+1:

Op woensdag 13 mei 2015 heeft Frodo Larik <notifications@github.com> het
volgende geschreven:

> Yes! that's what i mean, something like this in your config.xml
>
> <preference name="android-minSdkVersion" value="15" />
> <preference name="android-targetSdkVersion" value="19" />
>
> Android 5.x (target 21+) is still not used much.
>
> [image: iosvsandroidt]
> <https://camo.githubusercontent.com/ef2c505d0e9588772508b95a4212ed960ea9aa8c/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4345357a494b7556454141383031702e706e673a6c61726765>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kabisaict/maji/pull/36#issuecomment-101814047>.
>


-- 

Met vriendelijke groet,

Pascal Widdershoven
Kabisa

Marconilaan 8, 6003 DD, Weert
Kleine Gartmanplantsoen 10, 1017 RR, Amsterdam

email: pascal.widdershoven@kabisa.nl
web: http://www.kabisa.nl
mobile: +31 (0) 6 814 77 020
tel: +31 (0) 495 430 798
support tel: +31 (0) 495 430 593
support web: http://support.kabisa.nl
CoC: 14090089

**Comment by stefanvr** [comment]
The thing is: this configuration is not in the current maji project_template is there a no platform specific configuration included at the current time. 

So this will be a more fundamental question: do we want to include this, api config, to have a sane platform config when generating a maji application.

There are some implications on this:
- It needs to be maintained
- Users might not use a specific platform
- etc

**Comment by pascalw** [comment]
Please reopen against master.

**Pull request closed without merging**
