### PR TITLE
Update maji infrastructure

### PR DESCRIPTION
**Pull request by stefanvr**
- reorganise files
- add generic errors

Refactored with following end-structure in mind:

tree

### CODE REVIEW

**Comment by pascalw** [comment]
@stefanvr it seems that you're including the same commit in multiple PR's (for instance the JSONSettings commit). This makes it hard to accept some PR's but not others.

Can you try making the PR's self contained?

**Comment by stefanvr** [comment]
@pascalw done.

**Comment by pascalw** [comment]
Looks good to me. Not totally sure if we should include base error classes though, don't really see the point if they're not used by Maji itself.

**Comment by stefanvr** [comment]
Those error classes are also preparation. (more stuff to come ;-) )

**Pull request merged**
